version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "03:30"
      timezone: Etc/UTC
    allow:
      - dependency-type: all
    groups:
      kube:
        patterns:
          - k8s-openapi
          - kube
          - kube-*
        update-types: [major, minor]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
      time: "03:00"
      timezone: Etc/UTC
