version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "03:30"
      timezone: "UTC"
    allow:
      - dependency-type: "all"
    ignore:
      # We need to update all of these together, so we'll do it manually.
      - dependency-name: "kube*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
