[workspace]
resolver = "2"
default-members = [
    "kubert",
    "kubert-prometheus-process",
    "kubert-prometheus-tokio",
]
members = [
    "kubert",
    "kubert-prometheus-process",
    "kubert-prometheus-tokio",
    "examples",
]
